
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/.suo" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/Browse.VC.db" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/Solution.VC.db" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/24d46941e37cea49/OPENEXR_PREMIERE_EXPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/62d11bbb89f0bc55/OPENEXR_PREMIERE_IMPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/a19e227994fb280c/OPENEXR_PREMIERE_DIALOGS_WIN.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/b1247422920f323c/OPENEXR_PREMIERE_IO.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/c225cda21fd483ce/OPENEXR_PREMIERE_IO.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/d0e1d630d96773f3/OPENEXR_PREMIERE_IMPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/d1d501fd55321471/OPENEXR_UTF.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/OpenEXR_Premiere/v16/ipch/AutoPCH/d9aa71f2a23ec172/OPENEXR_PREMIERE_EXPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/.suo" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/Browse.VC.db" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/Solution.VC.db" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/ipch/AutoPCH/354355859117b15/OPENEXR_PREMIERE_IMPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/ipch/AutoPCH/58dfe5d55fe1eb/RAWDNG_UTF.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/ipch/AutoPCH/a9d2fe9f5aa00f37/RAWDNG_PREMIERE_IMPORT.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/ipch/AutoPCH/cf4ee37820d704cc/OPENEXR_PREMIERE_DIALOGS_WIN.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/.vs/RawDNG_Premiere/v16/ipch/AutoPCH/ec07d8ed9b2c0a1a/RAWDNG_PREMIERE_DIALOGS_WIN.ipch" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere.vcxproj.user" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Import_Dialog.res" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.log" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/CL.command.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/CL.read.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/CL.write.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/RawDNG_Premiere.lastbuildstate" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/RawDNG_Premiere.write.1u.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/link.command.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/link.read.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/link.write.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/rc.command.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/rc.read.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere.tlog/rc.write.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere_Dialogs_Win.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_Premiere_Import.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/RawDNG_UTF.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/RawDNG_Premiere/x64/Release/vc141.pdb" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/build/x64/Release/RawDNG_Premiere.exp" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/build/x64/Release/RawDNG_Premiere.lib" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/build/x64/Release/RawDNG_Premiere.pdb" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/build/x64/Release/zlib.lib" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/adler32.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/compress.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/crc32.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/deflate.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/gzclose.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/gzlib.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/gzread.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/gzwrite.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/infback.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/inffast.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/inflate.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/inftrees.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/trees.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/uncompr.obj" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.log" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.pdb" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/CL.command.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/CL.read.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/CL.write.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/Lib-link.read.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/Lib-link.write.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/Lib.command.1.tlog" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zlib.tlog/zlib.lastbuildstate" -- --all
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch vc/vc15/ext/zlib/x64/Release/zutil.obj" -- --all
